books/urls.py
from django.urls import path
from .views import book_list, book_detail, chapter_detail, exercise_detail

app_name = 'books'


urlpatterns = [
    path('', book_list, name='book_list'),
    path('<slug>/', book_detail, name='book_detail'),
    path('<book_slug>/<int:chapter_number>',
         chapter_detail, name='chapter_detail'),
    path('<book_slug>/<int:chapter_number>/<int:exercise_number>',
         exercise_detail, name='exercise_detail'),
]

django_digital_marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from core.views import profile_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('account/profile/', profile_view, name='profile_view'),
    path('', include('books.urls', namespace='books')),
    path('cart/', include('shopping_cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

shopping_cart/urls.py
from django.urls import path
from .views import add_to_cart, remove_from_cart, order_view, checkout

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/<slug:book_slug>', add_to_cart, name="add_to_cart"),
    path('remove-from-cart/<slug:book_slug>',
         remove_from_cart, name="remove_from_cart"),
    path('order-summary/', order_view, name='order_summary'),
    path('checkout/', checkout, name='checkout')
]

books/models.py
from django.db import models
from django.shortcuts import redirect, reverse
from django.conf import settings
from django.db.models.signals import post_save

# Create your models here.


class UserLibrary(models.Model):
    books = models.ManyToManyField('Book')
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def book_list(self):
        return self.books.all()

    class Meta:
        verbose_name = 'User Library'
        verbose_name_plural = 'User Library'


def post_user_signup_reciever(sender, instance, created, *args, **kwargs):
    if created:
        UserLibrary.objects.get_or_create(user=instance)


post_save.connect(post_user_signup_reciever, sender=settings.AUTH_USER_MODEL)


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    slug = models.SlugField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Book(models.Model):
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=100)
    publication_date = models.DateTimeField()
    isbn = models.CharField(max_length=16)
    slug = models.SlugField()
    cover = models.ImageField()
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book_detail", kwargs={
            'slug': self.slug
        })


class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:chapter_detail", kwargs={
            'book_slug': self.book.slug,
            'chapter_number': self.chapter_number
        })


class Exercise(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    exercise_number = models.IntegerField()
    page_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:exercise_detail", kwargs={
            'book_slug': self.chapter.book.slug,
            'chapter_number': self.chapter.chapter_number,
            'exercise_number': self.exercise_number
        })


class Solution(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    solution_number = models.IntegerField()
    image = models.ImageField()

    def __str__(self):
        return f"{self.exercise.title}-{self.pk}"

shopping_cart/models.py
from django.db import models
from django.conf import settings
from books.models import Book
from django.db.models import Sum


# Create your models here.

class OrderItem(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.book.title


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    ref_code = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

    def get_total(self):
        return self.items.all().aggregate(order_total=Sum('book__price'))['order_total']


class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    total_amount = models.FloatField()
    date_paid = models.DateTimeField(auto_now_add=True)
    stripe_charge_id = models.CharField(max_length=100)

    def __str__(self):
        return self.stripe_charge_id

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}{% endblock head_title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        {% include "navbar.html" %}
        {% block breadcrumb %}

        {% endblock breadcrumb %}
        {% include "messages.html" %}
        {% block content %}

        {% endblock content %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
            integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
            crossorigin="anonymous"></script>
    </div>
</body>

</html>

templates/book_detail.html
{% extends "base.html" %}
{% block head_title %}
Digital Marketplace
{% endblock head_title %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'books:book_list' %}">Book List</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{book.title}}</li>
    </ol>
</nav>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <main class="col-md-4">
        {% include "book_snippet.html" with book=book %}
    </main>
    <aside class="col-md-8">
        <div class="card">
            <div class="card-header">
                Chapter:
            </div>
            <ul class="list-group list-group-flush">
                {% for chapter in book.chapter_set.all %}
                <li class="list-group-item"><a
                        href="{{chapter.get_absolute_url}}">{{chapter.chapter_number}}.{{chapter.title}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </aside>
</div>

{% endblock content %}

templates/book_list.html
{% extends "base.html" %}
{% block head_title %}
Digital Marketplace
{% endblock head_title %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Book List</li>
    </ol>
</nav>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    {% for book in queryset %}
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{book.title}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{book.publication_date}}</h6>
                <p class="card-text">
                    {% for author in book.authors.all %}
                    <span>{{author}}</span>
                    {% if book.authors.count > 1 %} | {% endif %}
                    {% endfor %}
                </p>
                <a href="{{ book.get_absolute_url }}" class="card-link">{{book}}</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/book_snippet.html
<div class="card">
    <div class="card-header">{{book.title}}</div>
    <img src="{{book.cover.url}}" class="card-img-top">
    <div class="card-body">
        <p class="card-text">Published: {{book.publication_date}}</p>
    </div>
    {% if book_status != 'owned' %}
    {% if book_status == 'in_cart' %}
    <div class="card-footer">
        <a class="btn btn-danger btn-block" href="{% url 'cart:remove_from_cart' book.slug %}">Remove To
            Cart</a>
    </div>
    {% else %}
    <div class="card-footer">
        <a class="btn btn-warning btn-block" href="{% url 'cart:add_to_cart' book.slug %}">Add To Cart</a>
    </div>
    {% endif %}
    {% endif %}
</div>

templates/chapter_detail.html
{% extends "base.html" %}
{% block head_title %}
Digital Marketplace
{% endblock head_title %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'books:book_list' %}">Book List</a></li>
        <li class="breadcrumb-item"><a href="{{ chapter.book.get_absolute_url }}">{{chapter.book.title}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{chapter}}</li>
    </ol>
</nav>
{% endblock breadcrumb %}

{% block content %}

<div class="row">
    <main class="col-md-4">
        {% include "book_snippet.html" with book=chapter.book %}
    </main>
    <aside class="col-md-8">
        <div class="card">
            <div class="card-header">
                Exercise:
            </div>
            <ul class="list-group list-group-flush">
                {% for exercise in chapter.exercise_set.all %}
                <li class="list-group-item"><a
                        href="{{exercise.get_absolute_url}}">{{exercise.exercise_number}}.{{exercise.title}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </aside>
</div>
{% endblock content %}

templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% block head_title %}
Digital Marketplace
{% endblock head_title %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/stripe-form.css' %}">
<h4>Checkout</h4>
<hr>
<p>Order Total : ${{ order.get_total }}</p>

<script src="https://js.stripe.com/v3/"></script>

<form action="{% url 'cart:checkout' %}" method="post" id="payment-form">
    {% csrf_token %}
    <div class="stripe-form-row">
        <label for="card-element" class="stripe-label">
            Credit or debit card
        </label>
        <div id="card-element" class="StripeElement StripeElement--empty">
            <div class="__PrivateStripeElement"
                style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                <iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame1515"
                    allowpaymentrequest="true"
                    src="https://js.stripe.com/v3/elements-inner-card-1bc3c889dc7dea24f16327d0c47a90ca.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;wait=false&amp;rtl=false&amp;componentName=card&amp;keyMode=test&amp;apiKey=pk_test_51Hu9NQBDxIhqBJpO6wiam8hUTGLEUSUbb3xVCpGuNBCBNpKsKit9L2odyC2fq5OnR36XjEmxOEaGFPsIPaauuq3z000Ds1EzAw&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js&amp;controllerId=__privateStripeController1511"
                    title="Secure card payment input frame"
                    style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; user-select: none !important; transform: translateZ(0px) !important; height: 19.2px;"></iframe><input
                    class="__PrivateStripeElement-input" aria-hidden="true" aria-label=" " autocomplete="false"
                    maxlength="1"
                    style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
            </div>
        </div>

        <!-- Used to display form errors. -->
        <div id="card-errors" role="alert"></div>
    </div>

    <button type="submit">Submit Payment</button>
</form>

<script src="{% static 'js/stripe-form.js' %}"></script>

{% endblock content %}

templates/exercise_detail.html
{% extends "base.html" %}
{% load static %}
{% block head_title %}
Digital Marketplace
{% endblock head_title %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'books:book_list' %}">Book List</a></li>
        <li class="breadcrumb-item"><a
                href="{{ exercise.chapter.book.get_absolute_url }}">{{exercise.chapter.book.title}}</a>
        </li>
        <li class="breadcrumb-item"><a href="{{ exercise.chapter.get_absolute_url }}">{{exercise.chapter.title}}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">{{exercise.title}}</li>
    </ol>
</nav>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <main class="col-md-4">
        {% include "book_snippet.html" with book=exercise.chapter.book %}
    </main>
    <aside class="col-md-8">
        <div class="card">
            <div class="card-header">
                Solution:
            </div>
            {% if book_status == 'owned' %}

            {% for solution in exercise.solution_set.all %}

            <div class="accordion" id="solution-{{solution.solution_number}}">
                <div class="card">
                    <div class="card-header" id="heading-{{solution.solution_number}}">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                                data-target="#collapse-{{solution.solution_number}}" aria-expanded="true"
                                aria-controls="collapse-{{solution.solution_number}}">
                                Solution-{{solution.solution_number}}
                            </button>
                        </h2>
                    </div>


                    <div id="collapse-{{solution.solution_number}}" class="collapse" aria-labelledby="heading-{{solution.solution_number}"
                            data-parent="#solution-{{solution.solution_number}}">
                        <div class="card-body">
                            <img src="{{solution.image.url}}" class="card-img-top" alt="">
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            {% else %}
            <div class="text-center">
                <h5>You do not access to this book. <a href="#">Purchase this book</a> </h5>
                <img src="{% static 'images/lock.png' %}" alt="">
            </div>
            {% endif %}
        </div>
    </aside>
</div>
{% endblock content %}

templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}

templates/navbar.html
{% load cart_template_tags %}
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
    <a class="navbar-brand" href="{% url 'books:book_list' %}">Marketplace</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09"
        aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample09">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:order_summary' %}">{{ request.user|cart_item_count }}
                    <i class='fa fa-shopping-cart'></i>
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
        <a class="nav-link text-muted" href="{% url 'profile_view' %}">Account</a>
    </div>
</nav>

templates/order_summary.html
{% extends "base.html" %}
{% block head_title %}
Digital Marketplace
{% endblock head_title %}

{% block content %}
<h4>Order Summary</h4>
<hr>
<table class="table table-hover table-bordered text-center">
    <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Title</th>
            <th scope="col">Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item in order.items.all %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{item.book.title}}
                <a href="{% url 'cart:remove_from_cart' item.book.slug %}" class="text-danger"><i
                        class="fa fa-trash"></i></a>
            </td>
            <td>${{item.book.price}}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='3'>There are no items in your cart</td>
        </tr>
        {% endfor %}
        {% if order.get_total %}

        <tr>
            <td colspan="2">
                <strong class="pull-right">Order Total</strong>
            </td>
            <td><strong>
                    ${{order.get_total}}
                </strong></td>
        </tr>

        {% endif %}

        <tr>
            <td colspan="3">
                <a href="{% url 'books:book_list' %}" class="btn btn-warning">
                    {% if order %}
                    Continue Shopping
                    {% else %}
                    Add items to your Cart
                    {% endif %}
                </a>
            </td>
        </tr>
        {% if order.get_total %}
        <tr>
            <td colspan="3">
                <a href="{% url 'cart:checkout' %}" class="btn btn-primary">Checkout</a>
            </td>
        </tr>
        {% endif %}
    </tbody>
</table>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% block head_title %}
Digital Marketplace
{% endblock head_title %}

{% block content %}
<h4>Previous Orders</h4>
<hr>
<table class="table table-hover table-bordered text-center">
    <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Reference Code</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{order.ref_code}}</td>
            <td>${{order.get_total}}</td>
            <td>{{order.payment_set.first.date_paid}}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='3'>There are no items in your cart</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}